name: Android CI debug annd release build
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  SIGN_RELEASE_WITH_DEBUG_KEY_CI: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Set Gradle as executable
        run: chmod +x ./gradlew
      - name: Build Debug and Release APK
        run: ./gradlew assembleDebug assembleRelease
      - name: Output debug apk
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
      - name: Output release apks
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
